name: polleriadelivery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  crypto: ^3.0.1
  provider: ^6.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0  
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.0
  shared_preferences: ^2.2.2
  geocoding: ^3.0.0
  http: ^1.1.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/categorias/promociones/promo1.png
    - assets/images/categorias/promociones/promo2.png
    - assets/images/pollo.png
    - assets/images/carnes.png
    - assets/images/carnes2.png
    - assets/images/caldos.png
    - assets/images/lomo.png
    - assets/images/chicha.png
    - assets/images/papas.png
    - assets/images/postre.png
    - assets/images/promo.png
    - assets/images/verde.png
    - assets/images/fondopollo.jpg
    - assets/images/cargando.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Bold.ttf
        - asset: assets/fonts/Lora-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"
